# Generated by Django 5.0.2 on 2025-05-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0006_remove_eventos_fecha_fin_remove_eventos_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='responsable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
