# Generated by Django 5.0.2 on 2025-05-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0007_eventos_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='publico_objetivo',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
