# Generated by Django 5.0.2 on 2025-05-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0008_eventos_publico_objetivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='es_publico',
            new_name='publico',
        ),
    ]
