# Generated by Django 5.0.2 on 2025-05-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0009_rename_es_publico_eventos_publico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='publico',
            new_name='es_publico',
        ),
    ]
